version: '3'
services:
  openvpn:
    cap_add:
     - NET_ADMIN
    image: "myopenvpn:v1.0"
    build:
      context: "./docker"
      dockerfile: "./Dockerfile"
    container_name: openvpn
    ports:
     - 1194:1194/udp
    restart: always
    volumes:
     - ./openvpn-data/conf:/etc/openvpn:rw